projects:
  travutapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/lib/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: mh2wr7lbcrgiflvcxv26h4chvq
      endpoints:
        prod: >-
          https://jmglolv7ubdvvkf46fvsg7xieq.appsync-api.ap-northeast-2.amazonaws.com/graphql
