projects:
  travutapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/lib/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: 3jiiqe3amjdkhby4dtljx6yw5i
      endpoints:
        prod: >-
          https://mkdypagoo5fm7jn3rrkcw7whge.appsync-api.us-east-1.amazonaws.com/graphql
